[mypy]
files = bd_to_avp
exclude = ^bd_to_avp/vendor/pgsrip/

[mypy-ffmpeg]
ignore_missing_imports = True

[mypy-babelfish]
ignore_missing_imports = True

[mypy-bd_to_avp.vendor.pgsrip]
ignore_errors = True

[mypy-bd_to_avp.vendor.pgsrip.*]
ignore_errors = True
