AUTOMATIC_DIRECT_QUALITY = 0.7
AUTOMATIC_DIRECT_UPSCALE_QUALITY = 0.6
AUTOMATIC_GENERATED_EYE_BITRATE_MBPS = 20
AUTOMATIC_GENERATED_MERGE_QUALITY = 75
DEFAULT_AV1_CRF = 32
DEFAULT_UPSCALE_QUALITY = 75
